In [1]:
import numpy as np

In [9]:
# 1D Numpy Array - Creation
arr = np.array([ 1,2,3,4,5 ])
print(arr)

[1 2 3 4 5]


In [8]:
# 2D Numpy Array - Creation
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
# Array Properties
print("Shape:",arr2.shape) #(rows, columns)
print("Size:",arr2.size) #Total Elements
print("Data Type:",arr2.dtype) #Type of Elements

Shape: (2, 3)
Size: 6
Data Type: int64


In [19]:
# Array Operations
ar1 = np.array([1, 2, 3])
ar2 = np.array([4, 5, 6])
print("Addition:", ar1 + ar2)
print("Multiplication", ar1 * ar2) #General Multiplication PS: Not Dot Product

Addition: [5 7 9]
Multiplication [ 4 10 18]


In [21]:
# Dot Matrix - Matrix multiplication
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[5,6], [7,8]])
print(np.dot(mat1, mat2))

[[19 22]
 [43 50]]


In [22]:
print("Transpose:\n", mat1.T)

Transpose:
 [[1 3]
 [2 4]]


In [27]:
# Indexing and Slicing the Arrays
ar = np.array([10, 20, 30, 40, 50])
print(ar[1])
print(ar[1:4])

20
[20 30 40]


In [3]:
zeros = np.zeros((3, 3))
ones = np.ones((2, 2))
random_vals = np.random.rand(3, 3)

In [5]:
print(zeros)
print(ones)
print(random_vals)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.85019117 0.078665   0.59554192]
 [0.24791837 0.4295524  0.88742876]
 [0.81517088 0.67020014 0.28307339]]


In [3]:
arr = np.array([10, 20, 30, 40, 50])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))  # Sum of all elements
print(np.sum(matrix, axis=0))  # Sum by columns
print(np.sum(matrix, axis=1))  # Sum by rows

150
[5 7 9]
[ 6 15]
