In [1]:
import numpy as np

In [5]:
# TASK 1
# Create a 2D Matrix and Multiply by 2 

mat = np.array([[1,2,3], [4,5,6], [7,8,9]]) * 2
print(mat)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
# Task 2
# Create 2 1D Arrays
# multiply and sum for those both arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Sum: ", arr1 + arr2)
print("Multiply: ",arr1 * arr2)

Sum:  [5 7 9]
Multiply:  [ 4 10 18]


In [9]:
# Task 3
# Dot Product Matrix

ar1 = np.array([[1,2], [3,4]])
ar2 = np.array([[5,6], [7,8]])
print(np.dot(ar1, ar2))

[[19 22]
 [43 50]]


In [12]:
# Task 4
# Transpose Matrix

matT = np.array([[1,2], [3,4], [5,6]])
print(matT)
print("\n")
print(matT.T)

[[1 2]
 [3 4]
 [5 6]]


[[1 3 5]
 [2 4 6]]


In [14]:
# Task 5
# Create a matrix of Random Values 4x4
# Sum of elements, rows and columns

rmat = np.random.randint(1, 10, (4 , 4))
print(np.sum(rmat))
print(np.sum(rmat, axis = 0)) #Column Sum
print(np.sum(rmat, axis = 1)) #Row Sum

62
[14 12 17 19]
[18  9 18 17]
